import os
import cv2
import pydicom
from core_ml.inference_service import get_inference_service
from core_ml.chest_xray import get_chest_xray_analyzer
from core_ml.ecg import get_ecg_analyzer
from core_ml.blood_test import get_blood_test_analyzer
from core_ml.skin_analyzer import get_skin_analyzer
from core_ml.retinal_analyzer import get_retinal_analyzer
from core_ml.bone_xray_analyzer import get_bone_xray_analyzer
from core_ml.mri_classifier_analyzer import get_mri_classifier_analyzer

# Message shown whenever modality was *guessed* rather than confirmed from
# explicit metadata (a DICOM Modality tag) or an explicit filename keyword.
FALLBACK_WARNING = (
    "Could not confidently determine the scan type from the file. This result "
    "was generated by the default Brain CT/NCCT pipeline as a fallback — if "
    "this is not a brain CT scan, the analysis below is not meaningful. "
    "Please re-upload with a descriptive filename (e.g. 'chest_xray.jpg') or "
    "a DICOM file with a valid Modality tag."
)

ASPECT_RATIO_WARNING = (
    "Scan type was inferred from image shape/aspect ratio, not confirmed "
    "metadata or a filename keyword. Please verify this classification is "
    "correct before relying on the findings below."
)


class IngestionService:
    def __init__(self):
        pass

    def route_file(self, file_path: str, output_dir: str) -> dict:
        """
        Detect file modality and route to the correct parser/model.

        Returns:
            dict containing:
                'modality': str ('CT', 'CXR', 'ECG', 'BLOOD_TEST', 'DERMATO', 'RETINAL', 'BONE_XRAY')
                'result': dict (specific findings of the routed model)
                'modality_confidence': 'confirmed' | 'inferred' | 'default_fallback'
                'modality_warning': str | None (shown to the user when confidence is not 'confirmed')
        """
        ext = os.path.splitext(file_path.lower())[1]

        # 1. PDF Documents -> Blood/Lab test
        if ext == '.pdf':
            analyzer = get_blood_test_analyzer()
            res = analyzer.process_pdf(file_path)
            return {
                'modality': 'BLOOD_TEST',
                'result': res,
                'modality_confidence': 'confirmed',
                'modality_warning': None
            }

        # 2. DICOM Medical Files -> Check DICOM modality header tags
        if ext == '.dcm':
            try:
                ds = pydicom.dcmread(file_path, stop_before_pixels=True)
                modality_tag = str(getattr(ds, 'Modality', '')).upper()

                if 'ECG' in modality_tag:
                    analyzer = get_ecg_analyzer()
                    res = analyzer.process_image(file_path, output_dir)
                    return {
                        'modality': 'ECG',
                        'result': res,
                        'modality_confidence': 'confirmed',
                        'modality_warning': None
                    }
                elif 'CR' in modality_tag or 'DX' in modality_tag:
                    analyzer = get_chest_xray_analyzer()
                    res = analyzer.process_image(file_path, output_dir)
                    return {
                        'modality': 'CXR',
                        'result': res,
                        'modality_confidence': 'confirmed',
                        'modality_warning': None
                    }
                elif modality_tag and 'CT' not in modality_tag:
                    # DICOM explicitly declares a modality we don't have a
                    # pipeline for (e.g. MR, US) — do NOT silently run the
                    # brain CT model on it. Note: MRI IS supported for plain
                    # JPG/PNG uploads (see below) — DICOM-format MRI specifically
                    # isn't wired up yet (would need pixel windowing similar to
                    # the CT DICOM path before it can feed the JPG-trained classifier).
                    raise UnsupportedModalityError(
                        f"This file is tagged as DICOM modality '{modality_tag}'. NeuroDetect AI "
                        f"currently has validated pipelines for CT, CR/DX, and ECG DICOM files "
                        f"(MRI is supported for JPG/PNG uploads, but not yet for DICOM-format MRI). "
                        f"No analysis was run on this file."
                    )
            except UnsupportedModalityError:
                raise
            except Exception as e:
                print(f"[Ingestion] DICOM header read failed, falling back: {e}")

            # Default DICOM to Brain CT — only reached when the Modality tag
            # was missing/unreadable/CT-like, not when it named an unsupported modality.
            service = get_inference_service()
            res = service.process_image(file_path, output_dir)
            return {
                'modality': 'CT',
                'result': res,
                'modality_confidence': 'default_fallback',
                'modality_warning': FALLBACK_WARNING
            }

        # 3. Standard Images (JPG/PNG) -> Run keyword and visual heuristics router
        if ext in ['.jpg', '.jpeg', '.png']:
            filename = os.path.basename(file_path).lower()

            # Key 1: Filename Keyword checks (treated as confirmed — explicit user intent)
            if any(w in filename for w in ['ecg', 'electrocardiogram', 'rhythm', 'wave', 'lead']):
                analyzer = get_ecg_analyzer()
                res = analyzer.process_image(file_path, output_dir)
                return {'modality': 'ECG', 'result': res, 'modality_confidence': 'confirmed', 'modality_warning': None}
            elif any(w in filename for w in ['xray', 'cxr', 'chest', 'lung', 'pneumonia', 'pulmonary']):
                analyzer = get_chest_xray_analyzer()
                res = analyzer.process_image(file_path, output_dir)
                return {'modality': 'CXR', 'result': res, 'modality_confidence': 'confirmed', 'modality_warning': None}
            elif any(w in filename for w in ['skin', 'derm', 'lesion', 'mole', 'dermatology', 'melanoma', 'rash']):
                analyzer = get_skin_analyzer()
                res = analyzer.process_image(file_path, output_dir)
                return {'modality': 'DERMATO', 'result': res, 'modality_confidence': 'confirmed', 'modality_warning': None}
            elif any(w in filename for w in ['eye', 'retina', 'retinal', 'fundus', 'macula', 'optic', 'glaucoma']):
                analyzer = get_retinal_analyzer()
                res = analyzer.process_image(file_path, output_dir)
                return {'modality': 'RETINAL', 'result': res, 'modality_confidence': 'confirmed', 'modality_warning': None}
            elif any(w in filename for w in ['bone', 'fracture', 'joint', 'knee', 'femur', 'spine', 'ortho', 'skeletal']):
                analyzer = get_bone_xray_analyzer()
                res = analyzer.process_image(file_path, output_dir)
                return {'modality': 'BONE_XRAY', 'result': res, 'modality_confidence': 'confirmed', 'modality_warning': None}
            elif any(w in filename for w in ['mri', 'mr_', 'mr-']):
                # MRI now has a real (if not-yet-trained) pipeline — see
                # core_ml/mri_classifier_analyzer.py. It honestly reports
                # "not trained yet" until a real checkpoint is installed,
                # rather than either faking a result or hard-rejecting.
                analyzer = get_mri_classifier_analyzer()
                res = analyzer.process_image(file_path, output_dir)
                return {'modality': 'MRI', 'result': res, 'modality_confidence': 'confirmed', 'modality_warning': None}
            elif any(w in filename for w in ['brain', 'ct', 'ncct', 'head', 'stroke', 'slice']):
                service = get_inference_service()
                res = service.process_image(file_path, output_dir)
                return {'modality': 'CT', 'result': res, 'modality_confidence': 'confirmed', 'modality_warning': None}

            # Key 2: Visual Aspect-Ratio Heuristics — weaker evidence, always flagged as inferred
            try:
                img = cv2.imread(file_path, cv2.IMREAD_UNCHANGED)
                if img is not None:
                    h, w = img.shape[:2]
                    aspect_ratio = w / h

                    # ECG reports are typically wide scans
                    if aspect_ratio >= 1.6:
                        analyzer = get_ecg_analyzer()
                        res = analyzer.process_image(file_path, output_dir)
                        return {'modality': 'ECG', 'result': res, 'modality_confidence': 'inferred', 'modality_warning': ASPECT_RATIO_WARNING}
                    # Chest X-rays are typically vertical rectangular lung captures
                    elif aspect_ratio <= 0.88:
                        analyzer = get_chest_xray_analyzer()
                        res = analyzer.process_image(file_path, output_dir)
                        return {'modality': 'CXR', 'result': res, 'modality_confidence': 'inferred', 'modality_warning': ASPECT_RATIO_WARNING}
            except Exception as e:
                print(f"[Ingestion] Image dimension check failed: {e}")

            # Default to standard Brain CT pipeline — last resort, nothing matched.
            service = get_inference_service()
            res = service.process_image(file_path, output_dir)
            return {
                'modality': 'CT',
                'result': res,
                'modality_confidence': 'default_fallback',
                'modality_warning': FALLBACK_WARNING
            }

        raise ValueError(f"Unsupported report format extension: {ext}")


class UnsupportedModalityError(Exception):
    """Raised when the input is confidently identified as a modality this
    application has no validated analysis pipeline for (e.g. MRI). Callers
    should surface this message directly to the user rather than running an
    unrelated model and presenting its output as if it applied."""
    pass


_service = None

def get_ingestion_service() -> IngestionService:
    global _service
    if _service is None:
        _service = IngestionService()
    return _service
